app/__init__.py
import os

from flask import Flask, render_template
from flask_babel import Babel
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import BASEDIR

app = Flask(__name__)
app.config.from_object('config')

babel = Babel(app)
db    = SQLAlchemy(app)
lm    = LoginManager()

lm.session_protection = 'strong'
lm.login_view = 'auth.login'
lm.init_app(app)

@app.errorhandler(404)
def not_found(error):
	return render_template('404.html'), 404

@app.errorhandler(500)
def internal_server_error(e):
	return render_template('500.html'), 500

from app.main.controllers  import main  as main_module
from app.auth.controllers  import auth  as auth_module
from app.admin.controllers import admin as admin_module

# Register blueprint(s)
app.register_blueprint(main_module)
app.register_blueprint(auth_module)
app.register_blueprint(admin_module)

from auth import models

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, url_prefix='/admin')

app/admin/controllers.py
from flask import Blueprint, render_template, request, g, redirect, url_for
from flask_login import login_required
from flask_babel import gettext
from app.admin import admin

@admin.route('/')
@admin.route('/index')
def index():
	if g.user is not None and not g.user.is_administrator():
		return '<h1>No go zone for the unauthorized. Sorry.</h1>', 403

	return render_template('admin/index.html', 
		title=gettext('Admin'))

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, url_prefix='/')

app/main/controllers.py
from app import babel
from flask import Blueprint, render_template, request, g, redirect, url_for
from flask_login import login_required
from flask_babel import gettext
from config import LANGUAGES
from app.main import main

@babel.localeselector
def get_locale():
	return request.accept_languages.best_match(LANGUAGES.keys())

@main.route('/')
@main.route('index')
def index():
	if g.user is not None and g.user.is_authenticated:
		return redirect(url_for('main.dashboard'))

	return render_template('main/index.html', 
		title=gettext('Home'))

@main.route('privacy-policy')
def privacy():
	return render_template('main/privacy.html', 
		title=gettext('Privacy Policy'))

@main.route('dashboard')
@login_required
def dashboard():
	return render_template('main/dashboard.html', 
		title=gettext('Dashboard'))

@main.route('controllers')
@login_required
def controllers():
	return render_template('main/controllers.html', 
		title=gettext('Controllers'))

app/mod_public/controllers.py
from app import babel
from flask import Blueprint, render_template, request
from flask_babel import gettext
from config import LANGUAGES

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_public = Blueprint('public', __name__, url_prefix='/public')

@babel.localeselector
def get_locale():
	return request.accept_languages.best_match(LANGUAGES.keys())

@mod_public.route('/')
@mod_public.route('/index')
def index():
	return render_template('public/index.html', 
		title=gettext('Home'))

app/templates/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
    <title>{{ title }} - mono</title>
    {% else %}
    <title>{{ _('Welcome to idnet') }}</title>
    {% endif %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css', _external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/idnet.css', _external=True) }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css', _external=True) }}">
    {% if current_user.is_authenticated %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/idnet-private.css', _external=True) }}">
    {% else %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/idnet-public.css', _external=True) }}">
    {% endif %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/simple-line-icons.css', _external=True) }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename = 'ico/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename = 'ico/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename = 'ico/favicon-16x16.png') }}">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Slab:700|Source+Sans+Pro" rel="stylesheet">
 </head>
  <body>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissable" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <nav class="navbar navbar-expand-lg navbar-light static-top sb-navbar">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">mono</a>
            <button class="navbar-toggler navbar-toggler-right" 
                type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" 
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav mr-auto"></ul>
                <ul class="navbar-nav">
		    {% if current_user.is_authenticated %}
		    {% if current_user.is_administrator() %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.index') }}">{{ _('Admin') }}</a>
                    </li>
		    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ _('Log out') }}</a>
                    </li>
                    <li class="nav-item">
			<a class="nav-link">
                          <i class="fa fa-user"></i>
                          hi, {{ current_user.username }}
                        </a>
                    </li>
		    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">{{ _('Log in') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">or</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">{{ _('Sign up') }}</a>
                    </li>
		    {% endif %}
                </ul>
            </div>
    </nav>
    <main role="main">
        {% block content %}{% endblock %}
    </main>
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js', _external=True) }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js', _external=True) }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js', _external=True) }}"></script>
  </body>
</html>

app/templates/main/controllers.html
{% extends "base.html" %}
{% block content %}
<div class="navbar-2">
  <div class="row">
    <div class="col-md-12 text-center">
      <span class="float-md-left">
        <h1>{{ title }}</h1>
      </span>
    </div>
  </div>
</div>
<div class="container">
<a href=”/controllers”>View all controllers</a>
<br>
<a href=”/controllers/create”>Create a controller</a>
</div>
{% endblock %}

app/templates/main/dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="navbar-2">
  <div class="row">
    <div class="col-md-6 text-center">
      <span class="float-md-left">
        <h1>{{ title }}</h1>
      </span>
    </div>
    <div class="col-md-6 text-center">
      <span class="float-md-right">
        <a href="controllers" class="btn btn-primary">
          <i class="fa fa-cloud-upload icon-controller-button"></i>
          {{ _('Add controller') }}
        </a>
      </span>
    </div>  
  </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% block content %}
<div class="container jumbotron">
  <h2 class="small-caps">{{ _('Introducing the GDPR') }}</h2>
  <h1 class="display-3">{{ _('You\'re in control') }}</h1>
  <p class="lead">{{ _('The European Union has joined forces with companies and organisations - 
	everyone really - that hold data on you. Banks, social media Facebook and Google, 
	your city administration, hospital will now gladly give you access to the personal 
	data they have on you. That is tons of data. You will probably drown. 
	Use mono to vizualize what the web has on you.') }}</p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{{ url_for('auth.signup') }}" role="button">{{ _('Sign up') }} &raquo;</a>
    <a class="btn btn-outline-primary btn-lg" href="#" role="button">{{ _('Watch how it works') }}</a>
  </p>
  <p><a href="{{ url_for('auth.login') }}">{{ _('I already have an account') }}</a></p>
</div>
{% endblock %}

app/templates/main/privacy.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h1>{{title}}</h1>
<div class="wysiwyg"><p class="intro">At mono, we’re committed to protecting and respecting your privacy.</p>
<p>This Policy explains when and why we collect personal information about people who visit our website, how we use it, the conditions under which we may disclose it to others and how we keep it secure. It is a <strong>temporary for test purposes copy paste</strong> of https://www.ageuk.org.uk/help/privacy-policy/ as found via https://www.econsultancy.com/blog/69256-gdpr-how-to-create-best-practice-privacy-notices-with-examples.</p>
<p>We may change this Policy from time to time so please check this page occasionally to ensure that you’re happy with any changes. By using our website, you’re agreeing to be bound by this Policy.</p>
<p>Any questions regarding this Policy and our privacy practices should be sent by email to <a title="contact@mono.service" href="mailto:contact@mono.service">mono.service</a> or by writing to Customer Engagement, Av Richard Neybergh 17, 1020 Brussels. Alternatively, you can telephone 0800.</p>
<h2>Who are we?</h2>
<p>We’re mono, Europe's first charity dedicated to helping you exercise your Data Protection rights. mono is not registered yet.</p>
<h2>How do we collect information from you?</h2>
<p>We obtain information about you when you use our website, for example, when you upload data from a data collector.</p>
<h2>What type of information is collected from you?</h2>
<p>The personal information we collect might include your name, address, email address, information regarding what pages are accessed and when, location history, see Google, Microsoft... </p>
<h2>How is your information used?</h2>
<p>We exclusively use your information to:</p>
<ul>
<li>notify you of changes to our services;</li>
<li>let you analyze data collectors hold on you;</li>
<li>let you log in.</li>
</ul>
<p>We review our retention periods for personal information on a regular basis. We will hold your personal information on our systems for as long as is necessary for the relevant activity, or as long as is set out in any relevant contract you hold with us.</p>
<h2>Who has access to your information?</h2>
<p>We will not sell or rent your information to third parties.</p>
<p>We will not share your information with third parties for marketing purposes.</p>
<h2>Your choices</h2>
<p>We will not contact you for marketing purposes by email.</p>
<h2>How you can access and update your information</h2>
<p>The accuracy of your information is important to us. You have access to all information we hold on you after you log in. If you need any assistance email us <a title="contact@mono.service" href="mailto:contact@mono.service">mono.service</a> or you can telephone 0800. You can access your information, export it and (physically) delete it, in what we think is a very user friendly way.</p>
<p>You have the right to ask for a copy of the information mono holds about you. You can download your data after you log in.</p>
<h2>Security precautions in place to protect the loss, misuse or alteration of your information</h2>
<p>When you give us personal information, we take steps to ensure that it’s treated securely. All information is encrypted and protected.</p>
<h2>Profiling</h2>
<p>We analyse your personal information to create a profile of your interests and preferences so that you can analyze information your data collectors hold on you. We may make use of additional information about you when it is available from external sources to help us do this effectively. We may also use your personal information to detect and reduce fraud and credit risk.</p>
<h2>Use of 'cookies'</h2>
<p>Like many other websites, mono uses cookies. 'Cookies' are small pieces of information sent by an organisation to your computer and stored on your hard drive to allow that website to recognise you when you visit. They collect statistical data about your browsing actions and patterns and do not identify you as an individual. For example, we use cookies to store your country preference. This helps us to improve our website and deliver a better more personalised service.</p>
<p>It is possible to switch off cookies by setting your browser preferences. For more information on how to switch off cookies on your computer, visit&nbsp;our full cookies policy. Turning cookies of may result in a loss of functionality when using our website.</p>
<h2>Links to other websites</h2>
<p>Our website may contain links to other websites run by other organisations. This privacy policy applies only to our website‚ so we encourage you to read the privacy statements on the other websites you visit. We cannot be responsible for the privacy policies and practices of other sites even if you access them using links from our website.</p>
<p>In addition, if you linked to our website from a third party site, we cannot be responsible for the privacy policies and practices of the owners and operators of that third party site and recommend that you check the policy of that third party site.</p>
<h2>16 or Under</h2>
<p>We are concerned to protect the privacy of children aged 16 or under. If you are aged 16 or under‚ please get your parent/guardian's permission beforehand whenever you provide us with personal information.</p>
<h2>Transferring your information outside of Europe</h2>
<p>As part of the services offered to you through this website, the information which you provide to us may be transferred to countries outside the European Union (“EU”). By way of example, this may happen if any of our servers are from time to time located in a country outside of the EU. These countries may not have similar data protection laws to the EU. By submitting your personal data, you’re agreeing to this transfer, storing or processing. If we transfer your information outside of the EU in this way, we will take steps to ensure that appropriate security measures are taken with the aim of ensuring that your privacy rights continue to be protected as outlined in this Policy.</p>
<p>If you use our services while you are outside the EU, your information may be transferred outside the EU in order to provide you with those services.</p>
<h2>Review of this Policy</h2>
<p>We keep this Policy under regular review. This Policy was last updated in November 2017.</p>
</div>
</div>
{% endblock %}